[tool.poetry]
name = "deepgraphgen"
version = "0.1.0"
description = "tools to test graph generation"
authors = ["Adrien Bufort"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
